leftcamera_publisher:
  ros__parameters:
    serial: "45020167"
	  format: "video/x-raw"
	  pixelformat: "BGRX"
	  width: 1920
	  height: 1080
    framerate: 15/1
    properties:
      property:
        BalanceWhiteAuto:
         value: "Continuous"
      property: 
        ExposureAuto:
          value: "Off"
      property:
        GainAuto: 
          value: "Off"
      property:
        TriggerActivation:
          value: "Rising Edge"
      property:
        TriggerDelay: 
          value: 0.0
      property: 
        TriggerSelector: 
          value: "Exposure Active"
    
    imageprefix: "left"            

rightcamera_publisher:
  ros__parameters:
    serial: "45020169"
	  format: "video/x-raw"
	  pixelformat: "BGRX"
	  width: 1920
	  height: 1080
    framerate: 15/1
    properties:
      property:
        BalanceWhiteAuto:
         value: "Continuous"
      property: 
        ExposureAuto:
          value: "Off"
      property:
        GainAuto: 
          value: "Off"
      property:
        TriggerActivation:
          value: "Rising Edge"
      property:
        TriggerDelay: 
          value: 0.0
      property: 
        TriggerSelector: 
          value: "Exposure Active"
    
    imageprefix: "right" 