version: "2.0"
services:
    ros2_driver:
        image: ${ARCH}humble/ros2_driver:${TAG}
        build:
            context: /home/user/workspace/theimagingsource_ros/docker/
            dockerfile: Dockerfile.${ARCH}
        container_name: ros2_driver

