version: "1.0"
services:
    ros2_driver:
        image: ${ARCH}humble/ros2_driver:${TAG}
        build:
            context: ${PRODUCTION_PATH}/ros2_humble_docker/
            dockerfile: Dockerfile.${ARCH}
        container_name: ros2_driver

