version: "2.0"
services:
    ros2_driver:
        image: ${ARCH}humble/ros2_driver:${TAG}
        network_mode: host
        pid: host
        container_name: ros2_driver
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        user: root
        tty: true
        volumes:
            - type: bind
              source: /home/user/workspace/theimagingsource_ros/ros2_repos
              target: /home/theimagingsource_ros/ros2_repos
            - /dev:/dev:rw
            - type: bind
              source: /home/user/workspace/theimagingsource_ros/src/stereocam_publisher/launch
              target: /home/theimagingsource_ros/launch
            - type: bind
              source: /home/user/workspace/theimagingsource_ros/src/stereocam_publisher/config
              target: /home/theimagingsource_ros/config
            - type: bind
              source: /home/user/workspace/theimagingsource_ros/src/
              target: /home/theimagingsource_ros/src
        command: bash -c "
                   source /opt/ros/humble/setup.bash;
                   colcon build --packages-select stereocam_publisher;
                   source ./install/setup.bash;
                   ros2 launch stereocam_publisher launch.py
                   "

