version: "1.0"
services:
    cuda_ros:
        image: ${ARCH}humble/cuda_ros:${TAG}
        network_mode: host
        pid: host
        container_name: cuda_ros
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        user: root
        tty: true
        volumes:
            - /dev:/dev:rw
            
            - type: bind
              source: /home/oz/Downloads/theimagingsource_ros/cuda_ros2_repos/
              target: /home/cuda_ros/cuda_ros2_repos

        # command: bash -c "
        #            source /opt/ros/humble/setup.bash;
        #            colcon build --packages-select stereocam_publisher;
        #            source ./install/setup.bash;
        #            ros2 launch stereocam_publisher launch.py
        #            "

