leftcam:
  leftcamera_publisher:
    ros__parameters:
      serial: "45020167"
      imageprefix: "left"
      config_path: "/home/theimagingsource_ros/src/stereocam_publisher/config/camera_config.json"
  
rightcam:
   rightcamera_publisher:
    ros__parameters:
      serial: "45020169"
      imageprefix: "right"
      config_path: "/home/theimagingsource_ros/src/stereocam_publisher/config/camera_config.json"
